import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import {ClerkProvider} from "@clerk/nextjs";
const inter = Inter({ subsets: ['latin'] });



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  

  return (
      <html lang='en'>
      <ClerkProvider afterSignInUrl='/app' afterSignUpUrl='/app'>

      <body className={inter.className + 'overflow-x-hidden'}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
          >
            {children}
          </ThemeProvider>
        </body>
          </ ClerkProvider>
      </html>
  );
}
